/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hasibur Rahman
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCTextField1 = new app.bolivia.swing.JCTextField();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        jCTextField3 = new app.bolivia.swing.JCTextField();
        rSPasswordTextPlaceHolder1 = new rojerusan.RSPasswordTextPlaceHolder();
        rSPasswordTextPlaceHolder2 = new rojerusan.RSPasswordTextPlaceHolder();
        jCTextField4 = new app.bolivia.swing.JCTextField();
        jCTextField5 = new app.bolivia.swing.JCTextField();
        rSDateChooser1 = new rojeru_san.componentes.RSDateChooser();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        rSFotoCircle1 = new rojerusan.RSFotoCircle();
        jCheckBox1 = new javax.swing.JCheckBox();
        rSButtonIconD1 = new rojerusan.RSButtonIconD();
        rSButtonHover1 = new rojeru_san.complementos.RSButtonHover();
        rSButtonHover2 = new rojeru_san.complementos.RSButtonHover();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("Gender                   :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 170, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setText("First name            :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setText("Last name            :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 170, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setText("User name            :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel5.setText("Password               :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 170, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel6.setText("Confirm Password :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 170, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setText("Email                      :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 170, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setText("Contact                  :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 170, 30));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setText("Date Of Birth        :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 170, 30));

        jCTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextField1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jCTextField1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jCTextField1.setPhColor(new java.awt.Color(102, 102, 255));
        jCTextField1.setPlaceholder("Enter your username");
        jPanel1.add(jCTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 380, -1));

        jCTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextField2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jCTextField2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jCTextField2.setPhColor(new java.awt.Color(102, 102, 255));
        jCTextField2.setPlaceholder("***@gmail.com");
        jCTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 380, -1));

        jCTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextField3.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jCTextField3.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jCTextField3.setPhColor(new java.awt.Color(102, 102, 255));
        jCTextField3.setPlaceholder("Enter your last name");
        jCTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 380, -1));

        rSPasswordTextPlaceHolder1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        rSPasswordTextPlaceHolder1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        rSPasswordTextPlaceHolder1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        rSPasswordTextPlaceHolder1.setPhColor(new java.awt.Color(102, 153, 255));
        rSPasswordTextPlaceHolder1.setPlaceholder("Rewrite the password");
        jPanel1.add(rSPasswordTextPlaceHolder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 380, -1));

        rSPasswordTextPlaceHolder2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        rSPasswordTextPlaceHolder2.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        rSPasswordTextPlaceHolder2.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        rSPasswordTextPlaceHolder2.setPhColor(new java.awt.Color(102, 153, 255));
        rSPasswordTextPlaceHolder2.setPlaceholder("Enter a strong password");
        jPanel1.add(rSPasswordTextPlaceHolder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 380, -1));

        jCTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextField4.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jCTextField4.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jCTextField4.setPhColor(new java.awt.Color(102, 102, 255));
        jCTextField4.setPlaceholder("+880------------");
        jPanel1.add(jCTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 380, -1));

        jCTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jCTextField5.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jCTextField5.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jCTextField5.setPhColor(new java.awt.Color(102, 102, 255));
        jCTextField5.setPlaceholder("Enter your first name");
        jPanel1.add(jCTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 380, -1));

        rSDateChooser1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(rSDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 380, -1));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 610, -1, -1));

        rSFotoCircle1.setColorButtonOptionsHover(new java.awt.Color(0, 204, 0));
        jPanel1.add(rSFotoCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 240, 220));

        jCheckBox1.setFont(new java.awt.Font("Times New Roman", 0, 26)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("I agree, all the term and condition of service");
        jCheckBox1.setBorder(null);
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 690, 510, -1));

        rSButtonIconD1.setText("SUBMIT");
        rSButtonIconD1.setColorHover(new java.awt.Color(0, 204, 51));
        rSButtonIconD1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(rSButtonIconD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 750, 160, -1));

        rSButtonHover1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home_24px.png"))); // NOI18N
        rSButtonHover1.setText("Home");
        rSButtonHover1.setColorHover(new java.awt.Color(0, 0, 102));
        rSButtonHover1.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 750, 160, -1));

        rSButtonHover2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/icons8_Exit_26px_1.png"))); // NOI18N
        rSButtonHover2.setText("Cancle");
        rSButtonHover2.setColorHover(new java.awt.Color(255, 51, 51));
        rSButtonHover2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jPanel1.add(rSButtonHover2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 750, 160, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/501547.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 830));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 950, 830));

        jPanel2.setBackground(new java.awt.Color(0, 100, 198));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Impact", 1, 65)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Welcome to");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 370, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SignUp Page...");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 240, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Load/loading-gif-transparent.gif"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 310, 330));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Load/Join-Us-Now.gif"))); // NOI18N
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, 600, 400, 270));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        setSize(new java.awt.Dimension(1548, 875));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField2ActionPerformed

    private void jCTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextField1;
    private app.bolivia.swing.JCTextField jCTextField2;
    private app.bolivia.swing.JCTextField jCTextField3;
    private app.bolivia.swing.JCTextField jCTextField4;
    private app.bolivia.swing.JCTextField jCTextField5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private rojeru_san.complementos.RSButtonHover rSButtonHover1;
    private rojeru_san.complementos.RSButtonHover rSButtonHover2;
    private rojerusan.RSButtonIconD rSButtonIconD1;
    private rojeru_san.componentes.RSDateChooser rSDateChooser1;
    private rojerusan.RSFotoCircle rSFotoCircle1;
    private rojerusan.RSPasswordTextPlaceHolder rSPasswordTextPlaceHolder1;
    private rojerusan.RSPasswordTextPlaceHolder rSPasswordTextPlaceHolder2;
    // End of variables declaration//GEN-END:variables
}
